### ISSUE TITLE
github doesn't have an option to message users anymore

### ISSUE THREAD

**Issue by itsdeadguy** [Jipok/Jauth#1]
hi, sorry to bother you like this, but as per title... we talked briefly over a void linux issue regarding rocm. do you have email or irc/xmpp/discord i may reach you at? i didn't wanna clog void's  issue tracker any further

**Comment by Jipok** [comment]
You can write to me in telegram [@Jipok](https://t.me/Jipok), or by email to `void @ jipok.ru`(But I rarely check)
But I would recommend that you write either in the original issue(https://github.com/void-linux/void-packages/issues/26415) or in Rederick’s fork(https://github.com/rederick29/void-packages/issues/1), because he does all the work, I just successfully build for myself.
